maxmemory 200mb

# verwijderen van oud/minst gebruikte cache bij limit van 200mb
maxmemory-policy allkeys-lru 
#disable van disk syncronisation voor cpu te besparen
save ""

#deze zorgt ervoor dat redis op de achtergrond verlopen of grote cache files wist
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
