
server {
    listen 8080;
    server_name _;

    root /var/www/html/web;
    index index.php;

    set_real_ip_from 172.16.0.0/12;
    set_real_ip_from 10.0.0.0/8;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    

    # served de file direct of stuurt de URL naar index.php
    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ ^/sites/.*/files/styles/ {
        try_files $uri @drupal;
    }

    # verbied access tot verborgen bestanden
    location ~ (^|/)\. {
        deny all;
    }

    # verbied access tot php bestanden in bestanden map
    location ~* ^/sites/.*/files/.*\.php(?:/|$) {
        deny all;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS $http_x_forwarded_proto;
    }
}
