services:

  haproxy:
    image: haproxy:alpine
    container_name: drupal_haproxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./docker/haproxy/blocked_ips.txt:/usr/local/etc/haproxy/blocked_ips.txt:ro
      - ./docker/nginx/certs/combined.pem:/etc/ssl/certs/combined.pem:ro
      - ./docker/haproxy/domains.map:/usr/local/etc/haproxy/domains.map:ro
    networks:
      - haproxy_net
    deploy:
      resources:
       reservations:
         cpus: '0.05'
         memory: 32M
       limits:
         cpus: '0.5'
         memory: 128M
    depends_on:
      - varnish-a
      - varnish-b
    restart: unless-stopped


  php-init-a:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    container_name: drupal-init-a
    working_dir: /var/www/html
    restart: "no"
    volumes:
      - ./:/var/www/html:ro #bind
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
      - drupal_public_files:/var/www/html/web/sites/default/files:rw
      - drupal_multisite_a_files:/var/www/html/web/sites/multisite-a.local/files:rw
      - drupal_multisite_b_files:/var/www/html/web/sites/multisite-b.local/files:rw
    networks:
      - cluster_a_net
      - haproxy_net
    command: ["sh", "-ec", "chown -R 82:82 /var/www/html/web/sites/default/files /var/www/html/web/sites/multisite-a.local/files /var/www/html/web/sites/multisite-b.local/files"]


  php-a:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    user: "82:82"
    container_name: drupal-php-a
    working_dir: /var/www/html
    read_only: true
    tmpfs:
      - /tmp:exec
      - /run
    volumes:
      - ./:/var/www/html:rw #bind
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
      - drupal_public_files:/var/www/html/web/sites/default/files:rw
      - drupal_multisite_a_files:/var/www/html/web/sites/multisite-a.local/files:rw
      - drupal_multisite_b_files:/var/www/html/web/sites/multisite-b.local/files:rw
    networks:
      varnish-a-net:
      cluster_a_net:
        aliases:
          - php
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 256MB
        limits:
          cpus: '1.75'
          memory: 1024M
    depends_on:
      php-init-a:
        condition: service_completed_successfully
    restart: unless-stopped

  cron-a:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    working_dir: /var/www/html
    read_only: true
    tmpfs:
      - /tmp:exec
      - /run
    volumes:
      - ./:/var/www/html:ro
      - drupal_public_files:/var/www/html/web/sites/default/files:rw
      - drupal_multisite_a_files:/var/www/html/web/sites/multisite-a.local/files:rw
      - drupal_multisite_b_files:/var/www/html/web/sites/multisite-b.local/files:rw
    networks:
      - cluster_a_net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    depends_on:
      php-a:
        condition: service_started
    restart: unless-stopped


  nginx-a:
    image: nginxinc/nginx-unprivileged
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    volumes:
      - ./:/var/www/html:ro # bind
      - drupal_public_files:/var/www/html/web/sites/default/files:ro
      - drupal_multisite_a_files:/var/www/html/web/sites/multisite-a.local/files:ro
      - drupal_multisite_b_files:/var/www/html/web/sites/multisite-b.local/files:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #config
    networks:
      cluster_a_net:
        aliases:
          - nginx
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 96M
    depends_on:
      - php-a
    restart: unless-stopped

  varnish-a:
    image: varnish:fresh
    container_name: drupal_varnish_a
    volumes:
      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl:ro
    networks:
      haproxy_net:
      cluster_a_net:
        aliases:
          - varnish
    command: varnishd -F -a :80,PROXY -f /etc/varnish/default.vcl -s malloc,256m # start varnish protocol met config file en laat luisteren op MAX cache van 256MB
    deploy:
      resources:
        reservations:
          cpus: '0.10'
          memory: 256M
        limits: 
          cpus: '1.50'
          memory: 384M
    depends_on:
      - nginx-a
    restart: unless-stopped


  php-init-b:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    container_name: drupal-init-b
    working_dir: /var/www/html
    restart: "no"
    volumes:
      - ./:/var/www/html:ro #bind
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
      - drupal_multisite_c_files:/var/www/html/web/sites/multisite-c.local/files:rw
      - drupal_multisite_d_files:/var/www/html/web/sites/multisite-d.local/files:rw
      - drupal_domain_b_files:/var/www/html/web/sites/domain-b.local/files:rw
    networks:
      - cluster_b_net
    command: ["sh", "-ec", "chown -R 82:82 /var/www/html/web/sites/multisite-c.local/files /var/www/html/web/sites/multisite-d.local/files /var/www/html/web/sites/domain-b.local/files"]


  php-b:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    user: "82:82"
    container_name: drupal-php-b
    working_dir: /var/www/html
    read_only: true
    tmpfs:
      - /tmp:exec
      - /run
    volumes:
      - ./:/var/www/html:rw #bind
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
      - drupal_multisite_c_files:/var/www/html/web/sites/multisite-c.local/files:rw
      - drupal_multisite_d_files:/var/www/html/web/sites/multisite-d.local/files:rw
      - drupal_domain_b_files:/var/www/html/web/sites/domain-b.local/files:rw
    networks:
      haproxy_net:
      cluster_b_net:
        aliases:
          - php
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '1.75'
          memory: 1024M
    depends_on:
      php-init-b:
        condition: service_completed_successfully
    restart: unless-stopped

  cron-b:
    image: europe-west1-docker.pkg.dev/scalecity-sandbox-beau/image-repo/drupal-app:v1.0
    working_dir: /var/www/html
    read_only: true
    tmpfs:
      - /tmp:exec
      - /run
    volumes:
      - ./:/var/www/html:ro
      - drupal_multisite_c_files:/var/www/html/web/sites/multisite-c.local/files:rw
      - drupal_multisite_d_files:/var/www/html/web/sites/multisite-d.local/files:rw
      - drupal_domain_b_files:/var/www/html/web/sites/domain-b.local/files:rw
    networks:
      - cluster_b_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      php-b:
        condition: service_started
    restart: unless-stopped


  nginx-b:
    image: nginxinc/nginx-unprivileged
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    volumes:
      - ./:/var/www/html:ro # bind
      - drupal_multisite_c_files:/var/www/html/web/sites/multisite-c.local/files:ro
      - drupal_multisite_d_files:/var/www/html/web/sites/multisite-d.local/files:ro
      - drupal_domain_b_files:/var/www/html/web/sites/domain-b.local/files:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #config
    networks:
      cluster_b_net:
        aliases:
          - nginx
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 96M
    depends_on:
      - php-b
    restart: unless-stopped

  varnish-b:
    image: varnish:fresh
    container_name: drupal_varnish_b
    volumes:
      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl:ro
    networks:
      haproxy_net:
      cluster_b_net:
        aliases:
          - varnish 
    command: varnishd -F -a :80,PROXY -f /etc/varnish/default.vcl -s malloc,256m # start varnish protocol met config file en laat luisteren op 
    deploy:
      resources:
        reservations:
          cpus: '0.10'
          memory: 256M
        limits: 
          cpus: '1.50'
          memory: 384M
    depends_on:
      - nginx-b
    restart: unless-stopped

networks:
  cluster_a_net:
    driver: bridge
  cluster_b_net:
    driver: bridge
  haproxy_net:
    driver: bridge
  varnish-a-net:
    driver: bridge
  varnish-b-net:
    driver: bridge
  

volumes:
  drupal_public_files:
  drupal_multisite_a_files:
  drupal_multisite_b_files:
  drupal_multisite_c_files:
  drupal_multisite_d_files:
  drupal_domain_b_files:

  
